server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/user/**
        - id: DEPT-SERVICE
          uri: lb://DEPT-SERVICE
          predicates:
            - Path=/department/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url-defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
